import express from 'express';
import AICache from '../models/AICache.js';
import coachConversationEngine from '../services/ai/coachConversationEngine.js';

// Helper to normalize user queries
const normalizeQuery = (query) => {
  if (!query) return '';
  return query
    .toLowerCase()
    .replace(/[^\w\s]/gi, '')
    .replace(/\s+/g, ' ')
    .trim();
};

const GREETINGS = [
  'hi', 'hello', 'hey', 'hi there', 'hello there', 'hey coach', 'hi coach',
  'good morning', 'good evening', 'good afternoon', 'greetings', 'sup', 'yo',
  'how are you', 'how are you doing', 'how do you do', 'how is it going', 'whats up', 'what is up'
];

const isGreeting = (query) => {
  const normalized = normalizeQuery(query);
  return GREETINGS.some(g => normalized === g || normalized === `${g} ai` || normalized === `${g} bot`);
};

export const handleChat = async (req, res) => {
  try {
    const {
      message,
      userContext = {},
      history = [],
      currentPlan = null,
      currentWorkout = null,
      recentWorkoutHistory = [],
      currentProgress = {},
      preferences = {}
    } = req.body;

    if (!message || !message.trim()) {
      return res.status(400).json({ error: 'Message is required' });
    }

    const rawMessage = message.trim();

    // 1. RUN CONVERSATIONAL MEMORY & DECISION ENGINE (Acts as Sports Science Calculation & Safety Tool)
    const decisionResult = coachConversationEngine.processTurn({
      message: rawMessage,
      userContext,
      history,
      currentPlan,
      currentWorkout,
      recentWorkoutHistory,
      currentProgress,
      preferences
    });

    // 2. OLLAMA AS BOSS (Local LLM is primary conversational coach orchestrator)
    const enableOllama = process.env.ENABLE_OLLAMA === 'true' || Boolean(process.env.OLLAMA_HOST);
    const ollamaUrl = process.env.OLLAMA_HOST || 'http://localhost:11434/api/chat';
    const ollamaModel = process.env.OLLAMA_MODEL || 'qwen2.5:0.5b';

    if (enableOllama) {
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 12000);

        const userName = userContext?.name || userContext?.userName || 'Athlete';
        const primaryGoal = userContext?.primaryGoal || 'General Fitness';
        const fitnessLevel = userContext?.fitnessLevel || 'Beginner';
        const equipment = userContext?.equipmentAccess || 'Full Gym';
        const weight = userContext?.weight || userContext?.weightKg || 'Not specified';
        const safetyFlags = decisionResult.structuredAction?.safetyFlags || [];

        const systemPrompt = `You are the GymSync AI Lead Coach — an elite, knowledgeable, and empathetic personal fitness trainer.
USER PROFILE:
- Athlete Name: ${userName}
- Primary Goal: ${primaryGoal}
- Fitness Level: ${fitnessLevel}
- Equipment: ${equipment}
- Weight: ${weight} kg
${safetyFlags.length > 0 ? `- SAFETY ALERT: ${safetyFlags.join(', ')}` : ''}

COACHING DIRECTIVES:
1. Natural Persona: Act like a genuine human personal coach. Be encouraging, concise, and practical. NEVER repeat long boilerplate menus or rigid repetitive intro templates.
2. Language Matching: Seamlessly match the user's language. If they speak in Roman Urdu/Hindi (e.g. "hi coach", "kal training hai", "stamina chahiye", "mera weight 100 kg hai"), reply in fluent, natural Roman Urdu/Hindi. If they speak in English, reply in English.
3. Greetings: If the user simply greets you ("hi", "hello", "salam"), greet them warmly and personally, ask how their body and recovery feel today, and ask what they want to work on.
4. Vague Goals & Clarifications: If the user gives vague input (e.g., "I have training tomorrow" or "kal training hai"), ask what specific type of training it is before prescribing exercises.
5. Plan Explanation: If a workout or diet plan is generated by your sports science engine, explain it encouragingly with practical cues. Do not contradict safety rules or invent arbitrary numbers.

${decisionResult.structuredAction?.workout ? `[ENGINE WORKOUT GENERATED]: Focus: "${decisionResult.structuredAction.workout.sessionObjective}", Duration: ${decisionResult.structuredAction.workout.timeBudget || 45} mins. Exercises: ${(decisionResult.structuredAction.workout.mainWorkout || []).map(e => e.name).join(', ')}.` : ''}
${decisionResult.structuredAction?.diet ? `[ENGINE DIET GENERATED]: Calories: ${decisionResult.structuredAction.diet.targetCalories} kcal, Protein: ${decisionResult.structuredAction.diet.macronutrients?.proteinGrams}g, Carbs: ${decisionResult.structuredAction.diet.macronutrients?.carbsGrams}g, Fats: ${decisionResult.structuredAction.diet.macronutrients?.fatsGrams}g.` : ''}
${decisionResult.structuredAction?.explanation ? `[ENGINE RATIONALE]: ${decisionResult.structuredAction.explanation}` : ''}`;

        const ollamaMessages = [
          { role: 'system', content: systemPrompt },
          ...history.slice(-6).map(m => ({
            role: (m.role === 'user' || m.sender === 'user') ? 'user' : 'assistant',
            content: m.content || m.text || ''
          })).filter(m => m.content && m.content.trim()),
          { role: 'user', content: rawMessage }
        ];

        const ollamaRes = await fetch(ollamaUrl, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          signal: controller.signal,
          body: JSON.stringify({
            model: ollamaModel,
            messages: ollamaMessages,
            stream: false
          })
        });
        clearTimeout(timeoutId);

        if (ollamaRes.ok) {
          const data = await ollamaRes.json();
          const reply = data.message?.content?.trim();
          if (reply && reply.length > 5) {
            // Ollama successfully orchestrated the response as Boss!
            return res.status(200).json({
              role: 'assistant',
              content: reply,
              structuredAction: decisionResult.structuredAction
            });
          }
        }
      } catch (ollamaErr) {
        // Graceful fallback to deterministic coach engine if Ollama is unreachable/times out
        console.warn('Ollama unavailable or timed out, falling back to deterministic engine:', ollamaErr.message);
      }
    }

    // 3. DETERMINISTIC ENGINE FALLBACK (Used when Ollama is disabled or offline)
    if (isGreeting(rawMessage)) {
      const userName = userContext?.name || userContext?.userName || '';
      const greeting = `Hello${userName ? ` ${userName}` : ''}! 👋 I am your **GymSync AI Lead Coach & Sports Medicine Specialist**.

I have your complete biological profile loaded. I can assist you with:
- 🏋️ **Goal-driven, sport-specific workout plans** (Cricket, Football, Running, Hypertrophy, Fat Loss)
- 🩺 **Zero-tolerance joint & medical safety screening**
- 🥗 **Deterministic, mathematically verified macro & diet plans**
- ⚡ **Dynamic session adjustments** ("I have 20 mins", "Only dumbbells", "Knee discomfort", "Match tomorrow")

How are you feeling today, and what would you like to focus on?`;

      return res.status(200).json({
        role: 'assistant',
        content: greeting,
        structuredAction: { intent: 'greeting', workout: null, diet: null, safetyFlags: [], explanation: 'Initial coach greeting.' }
      });
    }

    return res.status(200).json({
      role: 'assistant',
      content: decisionResult.content,
      structuredAction: decisionResult.structuredAction
    });

  } catch (error) {
    console.error('AI Controller Error:', error);
    res.status(500).json({
      error: 'Failed to process AI request',
      message: error.message
    });
  }
};

export default { handleChat };
